# Lighthouse-Badger-Advanced | GitHub Action Workflow
#
# Description: Generates, adds & updates manually/automatically Lighthouse badges & reports from one/multiple input URL-group(s) to one/multiple target repo(s)/branch(es) in parallel
# Author: Sitdisch
# Source: https://github.com/myactionway/lighthouse-badger-workflows
# License: MIT
# Copyright (c) 2021 Sitdisch

name: 'Lighthouse-Badger-Advanced'

########################################################################
# DEFINE YOUR DEFAULTS (INPUTS & TRIGGERS) IN THE FOLLOWING
########################################################################

# INPUTS as environmental variables (env)
env:
  TOKEN_NAME: 'GH_TOKEN' # target token name; insert only the name never the real value e.g. 'LIGHTHOUSE_BADGER_TOKEN'
  # To change predefined values, just override them
  REPO_BRANCH: 'lobehub/lobe-chat lighthouse' # target repository & branch (predefined: repo with this file and master branch)
  USER_NAME: 'lobehubbot' # user who should commit
  USER_EMAIL: 'i@lobehub.com'
  AUDIT_TYPE: 'both' # 'mobile', 'desktop', 'both' or 'both_p'
  MOBILE_LIGHTHOUSE_PARAMS: '--throttling.cpuSlowdownMultiplier=2' # Lighthouse parameters mobile audit
  DESKTOP_LIGHTHOUSE_PARAMS: '--preset=desktop --throttling.cpuSlowdownMultiplier=1' # Lighthouse parameters desktop audit
  COMMIT_MESSAGE: '🤖 chore: Lighthouse Results Refreshed'

# TRIGGERS
on:
  workflow_dispatch:

########################################################################
# YOU CAN JUMP TO THE FIRST URL-GROUP DEFINITION BELOW
########################################################################

# Jobs
jobs:
  lighthouse-badger-advanced:
    name: ${{ matrix.NAME }}
    runs-on: ubuntu-22.04
    timeout-minutes: 8
    strategy:
      fail-fast: false
      matrix:
        include:
          - NAME: 'LobeChat | Welcome'
            URLS: 'https://chat-preview.lobehub.com/welcome'
            BADGES_ARGS: '-b pagespeed -o lighthouse/welcome -r'
            COMMIT_MESSAGE: '🤖 chore: Lighthouse Results | Welcome'
          - NAME: 'LobeChat | Chat'
            URLS: 'https://chat-preview.lobehub.com/chat'
            BADGES_ARGS: '-b pagespeed -o lighthouse/chat -r'
            COMMIT_MESSAGE: '🤖 chore: Lighthouse Results | Chat'
          - NAME: 'LobeChat | Market'
            URLS: 'https://chat-preview.lobehub.com/market'
            BADGES_ARGS: '-b pagespeed -o lighthouse/market -r'
            COMMIT_MESSAGE: '🤖 chore: Lighthouse Results | Market'
          - NAME: 'LobeChat | Settings'
            URLS: 'https://chat-preview.lobehub.com/settings'
            BADGES_ARGS: '-b pagespeed -o lighthouse/settings -r'
            COMMIT_MESSAGE: '🤖 chore: Lighthouse Results | Settings'
    ####################################################################
    # THAT'S IT; YOU DON'T HAVE TO DEFINE ANYTHING IN THE FOLLOWING
    ####################################################################
    steps:
      - name: Preparatory Tasks
        run: |
          REPOSITORY=`expr "${{ env.REPO_BRANCH }}" : "\([^ ]*\)"`
          BRANCH=`expr "${{ env.REPO_BRANCH }}" : ".* \([^ ]*\)"`
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        env:
          REPO_BRANCH: ${{ matrix.REPO_BRANCH || env.REPO_BRANCH }}
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          token: ${{ secrets[matrix.TOKEN_NAME] || secrets[env.TOKEN_NAME] }}
          ref: ${{ env.BRANCH }}
      - uses: actions/checkout@v3
        with:
          repository: 'myactionway/lighthouse-badges'
          path: temp_lighthouse_badges_nested
      - uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ matrix.URLS }}
          badges_args: ${{ matrix.BADGES_ARGS }}
          audit_type: ${{ matrix.AUDIT_TYPE || env.AUDIT_TYPE }}
          mobile_lighthouse_params: ${{ matrix.MOBILE_LIGHTHOUSE_PARAMS || env.MOBILE_LIGHTHOUSE_PARAMS }}
          desktop_lighthouse_params: ${{ matrix.DESKTOP_LIGHTHOUSE_PARAMS || env.DESKTOP_LIGHTHOUSE_PARAMS }}
          user_name: ${{ matrix.USER_NAME || env.USER_NAME }}
          user_email: ${{ matrix.USER_EMAIL || env.USER_EMAIL }}
          commit_message: ${{ matrix.COMMIT_MESSAGE || env.COMMIT_MESSAGE }}
          max_push_attempts: 5
